### ISSUE TITLE
For More than 17 items the Carousel Start Random Movements

### ISSUE THREAD

**Issue by sikandernoori** [jantepya/Carousel3D#2]
Hello @jantepya,

I am not sure what's causing this problem. But when you have items more than 17 the list start Random Movements on Click.

To Reproduce this issue Just increase number of elements in List.

```
for (var i = 0; i < 100; i++) {
				var img = document.createElement( 'img' );
				img.src = "./img/" + i + ".jpg";
				tileElements.push(img);
			}
```

**Comment by jantepya** [comment]
oh weird, I'll take a look over the weekend. I wrote this stuff really quickly a few years ago on a whim and haven't really looked at it since 😅

**Comment by sikandernoori** [comment]
Thank you @jantepya 

I think the issue is with below function:

```

Carousel3D.prototype.getSelected = function () {
	// if (this.tileElements.length > 12) {
	// 	return Math.floor((this.tileElements.length - 1) / 2) + this.tileOffset - 1;
	// }
	// else {
		return this.tileOffset + Math.floor((this.targets.length) / 2) - 1;
	// }
};
```

I have commented the if Condition after that the results are better but still offset drift when I try select an element from too far end of the list.

**Comment by jantepya** [comment]
I think it should be fixed now
